  
---
title: "Md. Amer Akhtab Muizz"
#author: "Amer Akhtab"
#date: "5/29/2020"
output:
  pdf_document: default

---
**Email**: amerakhtab@iut-dhaka.edu

**Phone**: +880 1758 719088

**Address**: 32/1, Azimpur Road, Azimpur, Dhaka-1205, Bangladesh

**LinkedIn**: https://www.linkedin.com/in/amer-akhtab-641150136  

**Github**: https://github.com/amerakhtab

---
## **Education**

> 2018-2020  
**Master of Business Administration (MBA)**  
Institute of Business Administration, University of Dhaka  
CGPA - 3.50 out of 4.00  

> 2014-2017  
**Bachelor of Science in Electrical and Electronic Engineering (B.Sc.Engg.)**  
Islamic University of Technology (IUT)  
CGPA - 3.70 out of 4.00 

> 2012-2013  
**Advanced Level (A Level) (Edexcel)**  
Maple Leaf International School  
Grades - 1A*, 2A, 1B (out of 4 subjects)  

>2010-2011  
**Ordinary Level (O Level) (Edexcel)**  
Maple Leaf International School  
Grades - 7A (out of 7 subjects)

## **Work Experience**

>November 2020-Present  
**Management Trainee Officer, E-valy.com limited**  
Assigned at the Audit & Compliance department. Working on big data analytics using R programming and supporting internal processes.  

## **Certifications**
Data Science Specialization at Coursera  
Completed Courses:

* The Data Scientist's Toolbox
* R Programming
* Getting and Cleaning Data
* Exploratory Data Analysis
* Reproducible Research

## **Awards**  
2014-2017 | Organization of Islamic Cooperation (OIC) Scholarship at IUT.  
2014 | The Daily Star Achievement Award (A level).  
2012 | The Daily Star Achievement Award (O level). 

## **Research Interests**
* Data analytics
* Machine learning
* Bioinformatics
* Biostatistics

## **Undergraduate Thesis**  
**Title**: Optimization of DRX power saving for LTE based IoT devices.  
**Supervisor**: Dr. Mohammad T. Kawser   
**Abstract**: One of the key challenges in machine type communication (MTC) is to reduce the energy consumption of the user equipment (UE). In LTE, the key technique to saving power and prolonging battery life is known as discontinuous reception (DRX). The configuration of the extended DRX (eDRX) cycle in Release 13 is a tradeoff between the delay in each session and the paging waste for a user equipment which has a velocity. The objective is to minimize the total battery usage all the while keeping the tradeoff with the delays and the paging wastage minimum as well.  

## **Extra-curricular Activities**
* 2014-Present | Associate Director at Ganim Int’l School, Mahmudpur, Jamalpur, Bangladesh.
* 2015-2018 | Contributing Writer at ‘The Weekend Independent’, supplement of a national daily newspaper, The Independent.
* 2017 | Head of Public Relations of Esonance 2017, a national festival organized at IUT.
* 2015 | Volunteer at logistics and food department of Esonance 2015.  

## **Technical Skills**
* Programming packages | C, C++, Matlab, R, Rstudio
* Computer aided design | PSpice, Proteus, Microwind, AutoCAD

## **Language Skills**
* Bengali (Native)
* English 

## **Test Scores**
* GRE - Quantitative reasoning 163, Verbal Reasoning 153, Analytical Writing 4.0
* IELTS - Band Overall 7.5. (Listening 8.5, Reading 8.5, Writing 6.5, Speaking 7)

## **Industrial Training** 
Under the supervision of the Department of EEE, IUT, completed the industrial training in November 2016 and obtained the grade A+. Training included industry visits and lectures from professionals in different fields.  

Organization | Area of Focus
-------------|---------------
Bangladesh Atomic Energy Commission (BAEC) | Overview of Nuclear Reactor, Reactor Operation, Isotope Generation  
Bangladesh Telecommunication Limited (BTCL) | Optical Fiber Communication, Wireless and Satellite Communication, Submarine Cable Distribution  
Adex Group of Industries | Manufacturing of Transformers, Switchgears, Relays and their Quality Testing  
Micro Fibre Group | Captive Power Station, Operation of a Garments Factory  
Bangladesh Power Development Board (BPDB) | Generation of Electrical Energy from Thermal, HydroNuclear Energy, Distribution of Electrical Power, Operation of a Thermal Power Station  

## **References**
>**Dr. Mohammad Tawhid Kawser**  
Professor  
Department of Electrical and Electronic Engineering  
Islamic University of Technology (IUT)   
Phone: +880 1742 205081  
Email: mkawser@hotmail.com  

>**Avijit Mallik**  
Assistant Professor  
Institute of Business Administration (IBA), University of Dhaka  
Phone: +88-02-9661900  
Email: avijit@iba-du.edu  

>**Mirza Fuad Adnan**  
Assistant Professor  
Department of Electrical and Electronic Engineering  
Islamic University of Technology (IUT)  
Phone: +880-2-9291254-59 (ext.-3212)  
Email: adnan16@iut-dhaka.edu
